# Generated by Django 5.0.6 on 2026-07-03 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('customer', 'Cliente'), ('admin', 'Administrador'), ('support', 'Soporte')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('free_trial', 'Prueba Gratis'), ('basic', 'Básico'), ('pro', 'Pro'), ('business', 'Business')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price_crc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_quote_limit', models.PositiveIntegerField(blank=True, help_text='Vacío = ilimitado', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['price_crc'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del negocio')),
                ('legal_id', models.CharField(blank=True, max_length=30, verbose_name='Cédula jurídica')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo de contacto')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cotizador/logos/', verbose_name='Logo')),
                ('color_primary', models.CharField(default='#1a3a5c', max_length=7, verbose_name='Color principal')),
                ('currency', models.CharField(choices=[('CRC', 'Colones (₡)'), ('USD', 'Dólares ($)')], default='CRC', max_length=3, verbose_name='Moneda')),
                ('footer_note', models.TextField(blank=True, verbose_name='Nota de pie de página')),
                ('sinpe_number', models.CharField(blank=True, max_length=20, verbose_name='Número SINPE Móvil')),
                ('sinpe_account_holder', models.CharField(blank=True, max_length=150, verbose_name='Titular de la cuenta SINPE')),
                ('next_quote_number', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('target_repr', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizador_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cotizador_app.business')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cotizador_app.business')),
            ],
            options={
                'verbose_name': 'Nota Interna',
                'verbose_name_plural': 'Notas Internas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='Empresa')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('identification', models.CharField(blank=True, max_length=30, verbose_name='Identificación')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='cotizador_app.business')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Fallido')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='cotizador_app.business')),
            ],
            options={
                'verbose_name': 'Registro de Correo',
                'verbose_name_plural': 'Registros de Correo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('tilopay', 'Tilopay'), ('paypal', 'PayPal'), ('sinpe', 'SINPE Móvil')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('approved', 'Aprobado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('rejected', 'Rechazado'), ('refunded', 'Reembolsado'), ('expired', 'Expirado')], default='pending', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='CRC', max_length=3)),
                ('external_reference', models.CharField(blank=True, help_text='ID de transacción del proveedor', max_length=120)),
                ('internal_reference', models.CharField(help_text='Referencia mostrada al cliente', max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cotizador_app.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cotizador_app.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('tilopay', 'Tilopay'), ('paypal', 'PayPal'), ('sinpe', 'SINPE Móvil')], max_length=10)),
                ('event_type', models.CharField(max_length=50)),
                ('external_event_id', models.CharField(max_length=150)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cotizador_app.payment')),
            ],
            options={
                'verbose_name': 'Evento de Pago',
                'verbose_name_plural': 'Eventos de Pago',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('tax_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Impuesto (%)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cotizador_app.business')),
            ],
            options={
                'verbose_name': 'Producto/Servicio',
                'verbose_name_plural': 'Productos/Servicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='draft', max_length=10)),
                ('issue_date', models.DateField(verbose_name='Fecha')),
                ('valid_until', models.DateField(verbose_name='Válida hasta')),
                ('currency', models.CharField(choices=[('CRC', 'Colones (₡)'), ('USD', 'Dólares ($)')], default='CRC', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('terms', models.TextField(blank=True, verbose_name='Términos y condiciones')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cotizador/pdfs/')),
                ('pdf_content_hash', models.CharField(blank=True, max_length=64)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='cotizador_app.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='cotizador_app.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador_app.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizador_app.quotation')),
            ],
            options={
                'verbose_name': 'Ítem de Cotización',
                'verbose_name_plural': 'Ítems de Cotización',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=43, unique=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_link', to='cotizador_app.quotation')),
            ],
            options={
                'verbose_name': 'Enlace Público de Cotización',
                'verbose_name_plural': 'Enlaces Públicos de Cotización',
            },
        ),
        migrations.CreateModel(
            name='SinpePaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_public_id', models.CharField(max_length=200)),
                ('resource_type', models.CharField(default='image', max_length=10)),
                ('mime_type', models.CharField(max_length=50)),
                ('file_size', models.PositiveIntegerField()),
                ('reference_number', models.CharField(max_length=50, verbose_name='Referencia SINPE')),
                ('payment_date', models.DateField(verbose_name='Fecha de pago')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('status', models.CharField(choices=[('pending_review', 'Pendiente de revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending_review', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinpe_receipts', to='cotizador_app.business')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sinpe_receipt', to='cotizador_app.payment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinpe_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comprobante SINPE',
                'verbose_name_plural': 'Comprobantes SINPE',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Prueba'), ('active', 'Activa'), ('past_due', 'Vencida'), ('canceled', 'Cancelada')], default='trialing', max_length=10)),
                ('billing_cycle_start', models.DateTimeField(blank=True, null=True)),
                ('billing_cycle_end', models.DateTimeField(blank=True, null=True)),
                ('quota_override', models.PositiveIntegerField(blank=True, help_text='Anula el límite del plan si se define', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='cotizador_app.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='cotizador_app.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField(blank=True, help_text='Vacío mientras está en prueba (conteo total, no mensual)', null=True)),
                ('quotations_used', models.PositiveIntegerField(default=0)),
                ('quota_limit', models.PositiveIntegerField(blank=True, help_text='Vacío = ilimitado', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='cotizador_app.business')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='cotizador_app.subscription')),
            ],
            options={
                'verbose_name': 'Registro de Uso',
                'verbose_name_plural': 'Registros de Uso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cotizador_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='cotizador_app.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizador_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['business', 'name'], name='cotizador_a_busines_2d33dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentevent',
            unique_together={('provider', 'external_event_id')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'name'], name='cotizador_a_busines_c7be3b_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['business', 'created_at'], name='cotizador_a_busines_11ae64_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['business', 'status'], name='cotizador_a_busines_0d0cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quote_number'], name='cotizador_a_quote_n_57fe24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('business', 'quote_number')},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['business', 'status'], name='cotizador_a_busines_a67c01_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='cotizador_a_status_5ce40f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['internal_reference'], name='cotizador_a_interna_354042_idx'),
        ),
        migrations.AddIndex(
            model_name='usagetracking',
            index=models.Index(fields=['business', 'created_at'], name='cotizador_a_busines_93cf55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
