# Generated by Django 5.0.6 on 2026-07-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_app', '0002_seed_roles_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio en dólares — usado para cobros por PayPal (no soporta colones) y otros países fuera de Costa Rica', max_digits=10),
        ),
    ]
