# Generated by Django 5.0.6 on 2026-07-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_app', '0003_subscriptionplan_price_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='currency',
            field=models.CharField(choices=[('CRC', 'Colones (₡) — Costa Rica'), ('NIO', 'Córdobas (C$) — Nicaragua'), ('GTQ', 'Quetzales (Q) — Guatemala'), ('HNL', 'Lempiras (L) — Honduras'), ('PAB', 'Balboas (B/.) — Panamá'), ('COP', 'Pesos colombianos ($) — Colombia'), ('PEN', 'Soles (S/) — Perú'), ('CLP', 'Pesos chilenos ($) — Chile'), ('ARS', 'Pesos argentinos ($) — Argentina'), ('BOB', 'Bolivianos (Bs) — Bolivia'), ('PYG', 'Guaraníes (₲) — Paraguay'), ('UYU', 'Pesos uruguayos ($U) — Uruguay'), ('VES', 'Bolívares (Bs) — Venezuela'), ('USD', 'Dólares ($)')], default='CRC', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='currency',
            field=models.CharField(choices=[('CRC', 'Colones (₡) — Costa Rica'), ('NIO', 'Córdobas (C$) — Nicaragua'), ('GTQ', 'Quetzales (Q) — Guatemala'), ('HNL', 'Lempiras (L) — Honduras'), ('PAB', 'Balboas (B/.) — Panamá'), ('COP', 'Pesos colombianos ($) — Colombia'), ('PEN', 'Soles (S/) — Perú'), ('CLP', 'Pesos chilenos ($) — Chile'), ('ARS', 'Pesos argentinos ($) — Argentina'), ('BOB', 'Bolivianos (Bs) — Bolivia'), ('PYG', 'Guaraníes (₲) — Paraguay'), ('UYU', 'Pesos uruguayos ($U) — Uruguay'), ('VES', 'Bolívares (Bs) — Venezuela'), ('USD', 'Dólares ($)')], default='CRC', max_length=3),
        ),
    ]
