# Generated by Django 5.0.6 on 2026-07-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_app', '0004_alter_business_currency_alter_quotation_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='legal_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='Cédula jurídica / ID fiscal'),
        ),
    ]
