# Generated by Django 5.0.6 on 2026-07-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_app', '0005_alter_business_legal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='quote_number_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
