# Generated by Django 5.0.6 on 2026-07-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_app', '0006_business_quote_number_reset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationsharelink',
            name='purchase_order_file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationsharelink',
            name='purchase_order_mime_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotationsharelink',
            name='purchase_order_public_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotationsharelink',
            name='purchase_order_resource_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='quotationsharelink',
            name='purchase_order_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
