# Generated by Django 5.0.6 on 2026-07-09 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_app', '0007_quotationsharelink_purchase_order_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='cotizador_app.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='currency',
            field=models.CharField(choices=[('CRC', 'Colones (₡) — Costa Rica'), ('NIO', 'Córdobas (C$) — Nicaragua'), ('GTQ', 'Quetzales (Q) — Guatemala'), ('HNL', 'Lempiras (L) — Honduras'), ('PAB', 'Balboas (B/.) — Panamá'), ('COP', 'Pesos colombianos ($) — Colombia'), ('PEN', 'Soles (S/) — Perú'), ('CLP', 'Pesos chilenos ($) — Chile'), ('ARS', 'Pesos argentinos ($) — Argentina'), ('BOB', 'Bolivianos (Bs) — Bolivia'), ('PYG', 'Guaraníes (₲) — Paraguay'), ('UYU', 'Pesos uruguayos ($U) — Uruguay'), ('VES', 'Bolívares (Bs) — Venezuela'), ('USD', 'Dólares ($)')], default='CRC', max_length=3, verbose_name='Moneda'),
        ),
    ]
