# Generated by Django 5.0.6 on 2026-07-10 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_app', '0008_alter_quotation_client_alter_quotation_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Banco')),
                ('currency', models.CharField(choices=[('CRC', 'Colones (₡) — Costa Rica'), ('NIO', 'Córdobas (C$) — Nicaragua'), ('GTQ', 'Quetzales (Q) — Guatemala'), ('HNL', 'Lempiras (L) — Honduras'), ('PAB', 'Balboas (B/.) — Panamá'), ('COP', 'Pesos colombianos ($) — Colombia'), ('PEN', 'Soles (S/) — Perú'), ('CLP', 'Pesos chilenos ($) — Chile'), ('ARS', 'Pesos argentinos ($) — Argentina'), ('BOB', 'Bolivianos (Bs) — Bolivia'), ('PYG', 'Guaraníes (₲) — Paraguay'), ('UYU', 'Pesos uruguayos ($U) — Uruguay'), ('VES', 'Bolívares (Bs) — Venezuela'), ('USD', 'Dólares ($)')], default='CRC', max_length=3, verbose_name='Moneda')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Cuenta corriente')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='cotizador_app.business')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['currency', 'sort_order', 'id'],
            },
        ),
    ]
