# Generated by Django 5.0.6 on 2026-07-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_app', '0009_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='onboarding_pending',
            field=models.BooleanField(default=False, help_text='Si está pendiente, el Dashboard muestra un recordatorio para completar el perfil del negocio.'),
        ),
    ]
