# Generated by Django 5.0.6 on 2026-07-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_app', '0010_business_onboarding_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='onboarding_prompts_shown',
            field=models.PositiveSmallIntegerField(default=0, help_text='Cuántas veces (de un máximo de 3 inicios de sesión) ya se mostró el recordatorio.'),
        ),
    ]
